Update sshpass.yml

diff --git a/.github/workflows/sshpass.yml b/.github/workflows/sshpass.yml
--- a/.github/workflows/sshpass.yml
+++ b/.github/workflows/sshpass.yml
@@ -25,5 +25,12 @@ jobs:
             output=$(sshpass -p "$password" ssh -o StrictHostKeyChecking=no "$username@$ssh" "pwd" 2>&1)
             echo "$output"
             
+            # Check for success or failure
+            if [[ $? -ne 0 ]]; then
+              echo "Error executing command on $username@$ssh"
+            else
+              echo "Successfully executed command on $username@$ssh"
+            fi
+            
             sleep 5  # Wait 5 seconds for delay
           done
